#
# docker-compose file for deploying OrangeHRM in Docker.
#

version: '3.8'
services:
  orangehrm:
    image: orangehrm/orangehrm:5.6
    container_name: orangehrm
    hostname: orangehrm.mydomain.com
    environment:
      - TZ="UTC"
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_USER=orangehrm
      - ORANGEHRM_DATABASE_PASSWORD=YOUR_ORANGEHRM_DB_PASSWORD
      - ORANGEHRM_DATABASE_NAME=orangehrmdb
    volumes:
      - ./orangehrm-data/data:/var/www/html/lib/confs
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11.1.4
    container_name: mariadb
    environment:
      - TZ="UTC"
      - MARIADB_ROOT_PASSWORD=YOUR_MARIADB_PASSWORD
      - MARIADB_USER=orangehrm
      - MARIADB_PASSWORD=YOUR_ORANGEHRM_DB_PASSWORD
      - MARIADB_DATABASE=orangehrmdb
    volumes:
      - ./maria-db/data:/var/lib/mysql
      - ./maria-db/backups:/var/lib/mariadb-backups
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  nginx-reverse-proxy:
    image: nginx:1.25.3
    container_name: nginx-reverse-proxy
    environment:
      - TZ="UTC"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/certs:/etc/pki/tls/configs-certs
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

